package com.zhiting.clouddisk.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhiting.clouddisk.db.FolderPassword;

import com.zhiting.clouddisk.db.FolderPasswordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig folderPasswordDaoConfig;

    private final FolderPasswordDao folderPasswordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        folderPasswordDaoConfig = daoConfigMap.get(FolderPasswordDao.class).clone();
        folderPasswordDaoConfig.initIdentityScope(type);

        folderPasswordDao = new FolderPasswordDao(folderPasswordDaoConfig, this);

        registerDao(FolderPassword.class, folderPasswordDao);
    }
    
    public void clear() {
        folderPasswordDaoConfig.clearIdentityScope();
    }

    public FolderPasswordDao getFolderPasswordDao() {
        return folderPasswordDao;
    }

}
